<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Sales Dashboard Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        @media print {
            .chart-canvas {
                width: 100% !important;
                height: 100% !important;
            }

            table {
                font-size: 10px;
                border-collapse: collapse !important;

            }

            table th,
            table td {
                border: 0.2px solid #dee2e6 !important;
                padding: 4px !important;
            }

            .card-title,
            .card-text {
                font-size: 10px;
            }

            h1 {
                font-size: 18px;
            }

            h2 {
                font-size: 16px;
            }

            h3 {
                font-size: 14px;
            }

            p,
            li {
                font-size: 10px;
            }
        }
    </style>
</head>

<body>

    <div class="container my-3" id="printableArea">
        <!-- Heading -->
        <div class="text-center mb-3">
            <h1 class="fw-bold">SALES DASHBOARD REPORT</h1>
            <h3>SellTrack</h3>
            <p>{{ ucfirst($request->type) }} Report | <span id="todayDate"></span></p>
        </div>

        <!-- Info -->
        <div class="mb-4">
            <p class="mb-1"><strong>Print Date: </strong> {{ \Carbon\Carbon::now()->translatedFormat('l, d F Y') }}
            </p>
            <p class="mb-1"><strong>Generated By: </strong> {{ auth()->user()->user_name }}</p>
            <p class="mb-1"><strong>Branch: </strong> {{ auth()->user()->user_branch->branch_name }}</p>
        </div>

        <!-- Detail -->
        <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between"><span>Total
                    Bills</span><strong>{{ $request->totalBill }}</strong></li>
            <li class="list-group-item d-flex justify-content-between"><span>Total Sales</span><strong>Rp
                    {{ number_format($request->grandTotal) }}</strong></li>
            <li class="list-group-item d-flex justify-content-between"><span>QR Payment</span><strong>Rp
                    {{ number_format($request->qrPayment) }}</strong>
            </li>
            <li class="list-group-item d-flex justify-content-between"><span>Cash Payment</span><strong>Rp
                    {{ number_format($request->cashPayment) }}</strong></li>
        </ul>

        <!-- Chart -->
        <h3>{{ ucfirst($request->type) }} Sales Performance</h3>
        <div class="chart">
            <canvas id="mixed-income" class="chart-canvas" height="300px"></canvas>
        </div>
        <!-- Top Products -->
        <h3 class="mt-5">Top Selling Products</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Product Code</th>
                    <th>Product Name</th>
                    <th>Total Selling</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $product)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $product->product_code }}</td>
                        <td>{{ $product->product_name }}</td>
                        <td>
                            @php
                                $totalOutgoing = 0;
                                if ($product->incoming_stocks) {
                                    foreach ($product->incoming_stocks as $incoming) {
                                        $totalOutgoing += $incoming->outgoing_stocks->sum('quantity');
                                    }
                                }
                                echo $totalOutgoing;
                            @endphp
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <!-- Recent Bills -->
        <h3 class="mt-5">Recent Bills</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Bill ID</th>
                    <th>Payment Method</th>
                    <th>Grand Total</th>
                    <th>Status</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($bills as $bill)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $bill->id }}</td>
                        <td>{{ $bill->payment->payment_type }}</td>
                        <td>Rp {{ number_format($bill->grand_total) }}</td>
                        <td>{{ $bill->payment->status }}</td>
                        <td>{{ $bill->created_at }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <script>
        $(document).ready(function() {
            const now = new Date();
            $('#todayDate').text(now.toLocaleDateString());
            $('#printDate').text(now.toLocaleString());

            let result = JSON.parse(@json($request->resultChart));

            const salesData = result['data'];
            const lineData = result['labels'];

            var mixedIncome = $("#mixed-income")[0].getContext("2d");
            const chart = new Chart(mixedIncome, {
                type: "line",
                data: {
                    labels: lineData,
                    datasets: [{
                        type: 'bar',
                        label: 'Bar Dataset',
                        data: salesData,
                        backgroundColor: '#393F6B',
                        borderRadius: 8,
                        borderSkipped: false,
                        barPercentage: 0.6,
                        categoryPercentage: 0.2,
                    }, {
                        type: 'line',
                        label: 'Line Dataset',
                        data: salesData,
                        borderColor: '#D9306A',
                        backgroundColor: '#D9306A',
                        borderWidth: 2,
                        fill: false,
                        tension: 0.4,
                        pointRadius: 0,
                        pointHoverRadius: 0,
                    }],
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            display: false,
                        }
                    },
                    interaction: {
                        intersect: false,
                        mode: 'index',
                    },
                    scales: {
                        y: {
                            grid: {
                                drawBorder: false,
                                display: true,
                                drawOnChartArea: true,
                                drawTicks: false,
                                borderDash: [5, 5],
                                color: '#e5e5e5'
                            },
                            ticks: {
                                suggestedMin: 0,
                                suggestedMax: 500,
                                beginAtZero: true,
                                padding: 10,
                                font: {
                                    size: 14,
                                    lineHeight: 2
                                },
                                color: "#737373"
                            },
                        },
                        x: {
                            grid: {
                                drawBorder: false,
                                display: true,
                                drawOnChartArea: true,
                                drawTicks: false,
                                borderDash: [5, 5]
                            },
                            ticks: {
                                display: true,
                                color: '#737373',
                                padding: 10,
                                font: {
                                    size: 14,
                                    lineHeight: 2
                                },
                            }
                        },
                    },
                },
            });

            let checkChartRendered = setInterval(function() {
                if (chart && chart.canvas && chart.canvas.width > 0 && chart.canvas.height > 0) {
                    clearInterval(checkChartRendered);
                    window.print();
                }
            }, 500);
        });
    </script>

</body>

</html>
