<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Products Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        @media print {
            table {
                font-size: 10px;
                border-collapse: collapse !important;

            }

            table th,
            table td {
                border: 0.2px solid #dee2e6 !important;
                padding: 4px !important;
            }

            .card-title,
            .card-text {
                font-size: 10px;
            }

            h1 {
                font-size: 18px;
            }

            h2 {
                font-size: 16px;
            }

            h3 {
                font-size: 14px;
            }

            p,
            li {
                font-size: 10px;
            }
        }
    </style>
</head>

<body>

    <div class="container my-3" id="printableArea">
        <!-- Heading -->
        <div class="text-center mb-3">
            <h1 class="fw-bold">PRODUCTS REPORT</h1>
            <h3>SellTrack</h3>
            {{-- <p> {{  \Carbon\Carbon::parse($startDate)->translatedFormat('l, d F Y') }} - {{  \Carbon\Carbon::parse($endDate)->translatedFormat('l, d F Y') }} </p> --}}
        </div>

        <!-- Info -->
        <div class="mb-4">
            <p class="mb-1"><strong>Print Date : </strong> {{ \Carbon\Carbon::now()->translatedFormat('l, d F Y') }}
            </p>
            <p class="mb-1"><strong>Generated By : </strong> {{ auth()->user()->user_name }}</p>
            <p class="mb-1"><strong>Branch : </strong> {{ auth()->user()->user_branch->branch_name }}</p>
        </div>

        <!-- Detail -->
        <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between"><span>Total
                    Product</span><strong>{{ $products->count() }}</strong></li>
            <li class="list-group-item d-flex justify-content-between"><span>Overall Product Stock</span><strong>
                    {{ collect($products)->flatMap(function ($product) {
                            return $product['incoming_stocks'];
                        })->sum('current_stocks') }}
                </strong></li>
        </ul>

        <!-- All Products -->
        <h3 class="mt-5">All Products</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Product Code</th>
                    <th>Product Name</th>
                    <th>Product Image</th>
                    <th>Price</th>
                    <th>Category</th>
                    <th>Stock</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $product)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $product->product_code }}</td>
                        <td>{{ $product->product_name }}</td>
                        <td>
                            @if ($product->product_img)
                                <img src="{{ asset('storage/' . $product->product_img) }}"
                                    style="width: 100px; height: 100px; object-fit: cover;"
                                    alt="{{ $product->product_name }}">
                            @else
                                <p>no img</p>
                            @endif
                        </td>
                        <td>Rp {{ number_format($product->price) }}</td>
                        <td>{{ $product->categories_id ? $product->product_category->category_name : 'category not found' }}
                        </td>
                        <td>{{ $product->incoming_stocks->sum('current_stocks') ?? 0 }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <!-- Products Close to expiry -->
        <h3 class="mt-5">Products Close to Expiry</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Product Code</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Initial Stocks</th>
                    <th>Current Stocks</th>
                    <th>Expired</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($closeExpired as $product)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $product->product_detail->product_code }}</td>
                        <td>{{ $product->product_detail->product_name }}</td>
                        <td>Rp {{ number_format($product->price) }}</td>
                        <td>{{ $product->initial_stocks }}</td>
                        <td>{{ $product->current_stocks }}</td>
                        <td>{{ $bill->member->phone_number ?? '-' }}</td>
                        <td>{{ $product->expired }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <!-- Products running low -->
        <h3 class="mt-5">Products Running Low</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Product Code</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Initial Stocks</th>
                    <th>Current Stocks</th>
                    <th>Expired</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($runningLow as $product)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $product->product_detail->product_code }}</td>
                        <td>{{ $product->product_detail->product_name }}</td>
                        <td>Rp {{ number_format($product->product_detail->price) }}</td>
                        <td>{{ $product->initial_stocks }}</td>
                        <td>{{ $product->current_stocks }}</td>
                        <td>{{ $product->expired }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <!-- Incoming -->
        <h3 class="mt-5">Incoming Stocks</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Incoming ID</th>
                    <th>Product Code</th>
                    <th>Product Name</th>
                    <th>Price</th>
                    <th>Initial Stocks</th>
                    <th>Current Stocks</th>
                    <th>Expired</th>
                    <th>Created At</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($incomingStocks as $incomingStock)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $incomingStock->id }}</td>
                        <td>{{ $incomingStock->product_detail->product_code }}</td>
                        <td>{{ $incomingStock->product_detail->product_name }}</td>
                        <td>Rp {{ number_format($incomingStock->product_detail->price) }}</td>
                        <td>{{ $incomingStock->initial_stocks }}</td>
                        <td>{{ $incomingStock->current_stocks }}</td>
                        <td>{{ $incomingStock->expired }}</td>
                        <td>{{ $incomingStock->created_at }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <!-- Outgoing -->
        <h3 class="mt-5">Outgoing Stocks</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Outgoing Stocks ID</th>
                    <th>Incoming Stocks ID</th>
                    <th>Product Code</th>
                    <th>Quantity</th>
                    <th>Bills ID</th>
                    <th>Status</th>
                    <th>Created At</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($outgoingStocks as $outgoingStock)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $outgoingStock->id }}</td>
                        <td>{{ $outgoingStock->incoming_stocks_id }}</td>
                        <td>{{ $outgoingStock->incoming_stock->product_detail->product_code }}</td>
                        <td>{{ $outgoingStock->quantity }}</td>
                        <td>{{ $outgoingStock->detail_bill->bills_id }}</td>
                        <td>{{ $outgoingStock->detail_bill->bill->payment->status }}</td>
                        <td>{{ $outgoingStock->created_at }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>
<script>
    window.onload = function() {
        setTimeout(() => {
            window.print();
        }, 500);
    };
</script>

</html>
